version: '2.3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
  # front:
    # image: nginx:stable-alpine
    # container_name: front
    # restart: always
    # volumes:
      # - ./front:/usr/share/nginx/html
    # networks:
      # - internal
  admin:
    image: nginx:stable-alpine
    container_name: admin
    restart: always
    volumes:
      - ./back-office:/usr/share/nginx/html
    networks:
      - internal
  # api:
    # build: ./api
    # container_name: api
    # restart: always
    # volumes:
      # - back-office:/usr/share/nginx/html
    # networks:
      # - internal

  mongo:
    image: mongo:3.6
    restart: always
    container_name: mongo
    volumes:
      - ./db:/data/db
    networks:
      - internal
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=secret
      - ME_CONFIG_SITE_BASEURL=/mongo-express/
    networks:
      - internal
networks:
  internal:
